blank_issues_enabled: false

contact_links:
  - name: New issue on mongodb/mongo-php-driver
    url: https://github.com/mongodb/mongo-php-driver/issues/new/choose
    about: Experiencing a problem with the MongoDB PHP extension? Please report it through the mongo-php-driver repository.
  - name: New issue on mongodb/mongo-php-library
    url: https://github.com/mongodb/mongo-php-library/issues/new/choose
    about: Experiencing a problem with the MongoDB PHP library? Please report it through the mongo-php-library repository.
  - name: MongoDB Developer Community Forums
    url: https://developer.mongodb.com/community/forums/
    about: For questions, discussions, or general technical support, visit the MongoDB Community Forums. The MongoDB Community Forums are a centralized place to connect with other MongoDB users, ask questions, and get answers.
  - name: MongoDB Atlas or Cloud Manager
    url: https://cloud.mongodb.com/user
    about: For technical support questions pertaining to MongoDB Atlas or Cloud Manager, please log into your MongoDB Cloud account and open a support ticket.
  - name: MongoDB Enterprise or Ops Manager
    url: https://support.mongodb.com/
    about: For technical support questions pertaining to MongoDB Enterprise or Ops Manager, please file a ticket through the MongoDB Support Portal.
  - name: Report a Security Vulnerability
    url: https://docs.mongodb.org/manual/tutorial/create-a-vulnerability-report
    about: If you believe you have discovered a vulnerability in MongoDB products or have experienced a security incident related to MongoDB products, please report the issue to aid in its resolution.
